import cherrypy
import json



class HelloWorld(object):
   @cherrypy.expose
   @cherrypy.tools.json_out()
   def index(self):
        return {"Hello World!": "Hello"}

   @cherrypy.expose
   @cherrypy.tools.json_out()
   def matrix_status(self):
      retval = [
         {
            'matrix':"FRAME-1",
            'state':"OK"
         },
         {
            'matrix':"FRAME-2",
            'state':"Not Connected"
         },
         {
            'matrix':"FRAME-3",
            'state':"OK"
         },
         {
            'matrix':"FRAME-4",
            'state'  :"OK"
         }]
      return retval

   @cherrypy.expose
   @cherrypy.tools.json_out()
   def is_updated(self):
        retval = [{   'id':'0001',
                      'name':'ION 1',
                      'state':'updated',
                  },{
                      'id':'0002',
                      'name':'Frame A',
                      'state':'NotConnected',
                  }]
        return retval

   @cherrypy.expose
   @cherrypy.tools.json_out()
   def get_page(self, matrix, panel):
         print(panel)
         print(matrix)
         
         if panel=='DTV_C4' and matrix=='FRAME-4':
             
             retval = [
                          {
                            'key':0,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':1,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_B",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':2,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_C",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':3,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':4,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':5,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':6,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':7,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':8,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':9,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':10,
                            'page':5,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':11,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':12,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':13,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':14,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':15,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':16,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':17,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':18,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':19,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':20,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':21,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':22,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':23,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },

                        ]
                    
             return retval

         if panel=='DECOM_A' and matrix=='FRAME-3':
             
            retval = [
                        {
                           'key':0,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':1,
                           'page':1,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_B",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':2,
                           'page':1,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_C",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':3,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':4,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':5,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':6,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':7,
                           'page':4,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':8,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':9,
                           'page':4,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':10,
                           'page':5,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':11,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':12,
                           'page':6,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':13,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':14,
                           'page':6,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':15,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':16,
                           'page':2,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':17,
                           'page':2,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':18,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':19,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':20,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':21,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':22,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':23,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':24,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':25,
                           'page':1,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_B",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':26,
                           'page':1,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_C",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':27,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':28,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':29,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':30,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':31,
                           'page':4,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':32,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':33,
                           'page':4,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':34,
                           'page':5,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':35,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':36,
                           'page':6,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':37,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':38,
                           'page':6,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':39,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':40,
                           'page':2,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':41,
                           'page':2,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':42,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':43,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':44,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':45,
                           'page':3,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':46,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                        {
                           'key':47,
                           'page':0,
                           'system_id': 1,
                           'portnumber': 20,
                           'label':"DECOM_A",
                           'frame':"Frame 4",
                           'activation':"Talk",
                        },
                           
                           ]
                    
            return retval

         if panel=='DECOM_C' and matrix=='FRAME-3':
             
            retval = [
                          {
                            'key':0,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':1,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_B",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':2,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_C",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':3,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':4,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':5,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':6,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':7,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':8,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':9,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':10,
                            'page':5,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':11,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':12,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':13,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':14,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':15,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':16,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':17,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':18,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':19,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':20,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':21,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':22,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':23,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':24,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':25,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_B",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':26,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_C",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':27,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':28,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':29,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':30,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':31,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':32,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':33,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':34,
                            'page':5,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':35,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':36,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':37,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':38,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':39,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':40,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':41,
                            'page':2,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':42,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':43,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':44,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':45,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':46,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':47,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':48,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':49,
                            'page':7,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_B",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':50,
                            'page':1,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_C",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':51,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':52,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':53,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':54,
                            'page':3,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':55,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':56,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':57,
                            'page':4,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':58,
                            'page':5,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':59,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':60,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':61,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':62,
                            'page':6,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          {
                            'key':63,
                            'page':0,
                            'system_id': 1,
                            'portnumber': 20,
                            'label':"DECOM_A",
                            'frame':"Frame 4",
                            'activation':"Talk",
                          },
                          
                        ]
                    
            return retval

         else:
             return {'status':'not found','pages':{}}

   def cors():
     if cherrypy.request.method == 'OPTIONS':
      # preflign request 
      # see http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0
       cherrypy.response.headers['Access-Control-Allow-Methods'] = 'POST,GET'
       cherrypy.response.headers['Access-Control-Allow-Headers'] = 'content-type'
       cherrypy.response.headers['Access-Control-Allow-Origin']  = '*'
       # tell CherryPy no avoid normal handler
       return True
     else:
       cherrypy.response.headers['Access-Control-Allow-Origin'] = '*'

   cherrypy.tools.cors = cherrypy._cptools.HandlerTool(cors)
    
   @cherrypy.expose
   @cherrypy.tools.json_in()
   @cherrypy.tools.json_out()
   @cherrypy.tools.accept(media='application/json')
   @cherrypy.config(**{'tools.cors.on': True})

   def change_keys(self):
     data = cherrypy.request.json
     print(data)
     return data




#cherrypy.quickstart(HelloWorld())
cherrypy.server.socket_host = '10.8.0.8'
if __name__ == '__main__':
    conf = {
        '/': {
            'tools.response_headers.on': True,
            'tools.response_headers.headers': [('Content-Type', '*'), ('Access-Control-Allow-Origin', '*'), ('Access-Control-Allow-Methods', 'DELETE, POST, GET, OPTIONS')],
            'server.socket_port': 8080
        }
    }
    cherrypy.quickstart(HelloWorld(), '/', conf)
